export const plans = [
    {
        id: "starter",
        name: "Starter",
        price: 0,
        priceDisplay: "0",
        description: "Trial usage with CIAM suite",
        monthlyActiveUsers: 500,
        freeOrgs: 0,
        freeWorkspaces: 0,
        rateLimit: "50 req/min",
        features: [
            "500 MAU included",
            "1,000 Emails/mo",
            "50 req/min Rate Limit",
            "Core CIAM Suite",
        ],
        limits: {
            mau: 500,
            orgs: 0,
            workspaces: 0,
            webhooks: 0,
            emails: 1000,
            api_keys: 0,
        },
        overages: {} as any
    },
    {
        id: "pro",
        name: "Pro",
        price: 25,
        priceDisplay: "25",
        description: "All Features except consumer API keys",
        monthlyActiveUsers: 10000,
        freeOrgs: 500,
        freeWorkspaces: 2500,
        rateLimit: "100 req/min",
        features: [
            "10,000 MAU included",
            "500 Organizations",
            "2,500 Workspaces",
            "500 Consumer Webhook Apps",
            "100k Webhooks/mo",
            "100 req/min Rate Limit",
        ],
        limits: {
            mau: 10000,
            orgs: 500,
            workspaces: 2500,
            webhooks: 100000,
            emails: 0,
            api_keys: 0,
        },
        overages: {
            mau: "0.02 USD /user",
            orgs: "0.75 USD /org",
            workspaces: "0.75 USD /workspace",
            emails: "1.20 USD /1k emails",
            webhooks: "0.12 USD /1k reqs",
        } as any
    },
    {
        id: "growth",
        name: "Growth",
        price: 99,
        priceDisplay: "99",
        description: "Full Platform Access",
        popular: true,
        monthlyActiveUsers: 50000,
        freeOrgs: 3000,
        freeWorkspaces: 15000,
        rateLimit: "500 req/min",
        features: [
            "50,000 MAU included",
            "3,000 Organizations",
            "15,000 Workspaces",
            "4,000 Consumer Webhook Apps",
            "1M Webhooks/mo",
            "Unlimited Consumer API Apps",
            "60k req/min Rate Limit",
            "90 Days Log Retention",
            "API Checks: $0.2/10k",
            "Storage: $0.12/GB",
        ],
        limits: {
            mau: 50000,
            orgs: 3000,
            workspaces: 15000,
            webhooks: 1000000,
            emails: 0,
            api_keys: undefined,
        },
        overages: {
            mau: "0.02 USD /user",
            orgs: "0.50 USD /org",
            workspaces: "0.50 USD /workspace",
            emails: "1.20 USD /1k emails",
            webhooks: "0.10 USD /1k reqs",
            api_keys: "0.20 USD /10k checks",
            storage: "0.12 USD /GB",
        } as any
    },
];

export const enterprisePlan = {
    id: "enterprise",
    name: "Enterprise",
    price: null,
    priceDisplay: "Custom",
    description: "For large-scale deployments",
    monthlyActiveUsers: "Custom",
    features: [
        "Unlimited volume",
        "Dedicated support",
        "Custom contracts",
        "SLA Guarantee",
        "On-premise deployment options"
    ],
    rateLimit: "Custom",
    limits: {
        mau: 0,
        orgs: 0,
        workspaces: 0,
        webhooks: 0,
        emails: 0,
        api_keys: 0,
    },
    overages: undefined as any
};
